---
ANSIBLE_USERNAME:  admin
ANSIBLE_PASSWORD:  admin
ANSIBLE_VMR_SEMP_PORT: 8080
ANSIBLE_VMR_IP: 127.0.0.1
LOCAL_INFO:
   NAME: SOLACE_LOCAL_NAME
   ROLE: SOLACE_LOCAL_ROLE
PRIMARY_ROUTER:
   NAME: SOLACE_PRIMARY_NAME
   IP:   SOLACE_PRIMARY_IP
BACKUP_ROUTER:
   NAME: SOLACE_BACKUP_NAME
   IP:   SOLACE_BACKUP_IP
MONITOR:
   NAME: SOLACE_MONITOR_NAME
   IP:   SOLACE_MONITOR_IP
