---
#configure
#router-name <name>
- hosts: LOCALHOST

  tasks:
    - name: Set router name
      uri:
         url:              "http://{{ ANSIBLE_VMR_IP }}:{{ ANSIBLE_VMR_SEMP_PORT }}/SEMP"
         method:           GET
         user:             "{{ ANSIBLE_USERNAME }}"
         password:         "{{ ANSIBLE_PASSWORD }}"
         body:             "<rpc semp-version='soltr/8_2VMR'>\
                           <router-name><name>{{ LOCAL_INFO.ROLE }}</name></router-name></rpc>"
         force_basic_auth: yes
         status_code:      200
         body_format:      raw
         return_content:   yes
      register: rpc_reply
      ignore_errors: True
      until: rpc_reply.content.find("code=\"ok\"") != -1
      retries: 60
      delay: 10