---
#reload default-config monitoring-node
- hosts: LOCALHOST

  tasks:
    - name: Reboot VMR to Monitor node mode 
      uri:
         url:              "http://{{ ANSIBLE_VMR_IP }}:{{ ANSIBLE_VMR_SEMP_PORT }}/SEMP"
         method:           GET
         user:             "{{ ANSIBLE_USERNAME }}"
         password:         "{{ lookup('env','admin_password') }}"
         body:             "<rpc semp-version='soltr/8_2VMR'><reload><default-config/><monitoring-node/></reload></rpc>"
         force_basic_auth: yes
         status_code:      200
         body_format:      raw
         return_content:   yes
      register: rpc_reply
      ignore_errors: True
      until: rpc_reply.content.find("code=\"ok\"") != -1s
      retries: 60
      delay: 10
